//
//  CPFValidator.swift
//  CPF-CNPJ-TOOLS
//
//  Created by Diggo Silva on 16/11/24.
//

import Foundation

/// Enum representing the different statuses of a CPF after validation.
public enum CPFStatus {
    case valid         // Valid CPF.
    case invalid       // Invalid CPF.
    case cpfNull       // CPF cannot be null or empty.
    case equalDigits   // CPF with repeated digits is not valid (e.g., 111.111.111-11, which is invalid because it's a repeated number).
    case invalidFormat // Invalid CPF.\nCPF must have 11 digits (only numbers).
}

/// Manages operations related to `CPF (Brazilian Taxpayer ID), such as validation, generation, and formatting.
public class CPFManager {
    
    public init() {}
    
    /// Validates a given CPF, checking if it is valid, properly formatted, and if the verification digits are correct.
    ///
    /// - Parameter cpf: The CPF to be validated. It may contain non-numeric characters (dots, hyphens, etc.).
    /// - Returns: A `CPFStatus` value indicating the validation status.
    ///
    /// The `CPFStatus` enum can have the following values:
    /// - `.valid`: Indicates the CPF is valid.
    /// - `.invalid`: Indicates the CPF is invalid.
    /// - `.cpfNull`: Indicates the CPF is empty.
    /// - `.invalidFormat`: Indicates the CPF has an invalid format (wrong number of digits, contains letters, etc.).
    /// - `.equalDigits`: Indicates the CPF contains the same digit repeated (e.g., "111.111.111-11").
    ///
    ///  **Example:**
    /// ```swift
    /// let cpfManager = CPFManager()
    /// let status = cpfManager.validate(cpf: "111.444.777-35")
    /// print(status)  // .valid or .invalid
    /// ```
    public func validate(cpf: String) -> CPFStatus {
        let cleanedCPF = cpf.replacingOccurrences(of: "[^0-9]", with: "", options: .regularExpression)
        
        guard !cleanedCPF.isEmpty else { return .cpfNull }
        
        guard cleanedCPF.count == 11, cleanedCPF.allSatisfy({ $0.isNumber }) else { return .invalidFormat }
        
        if Set(cleanedCPF).count == 1 { return .equalDigits }
        
        let digits = cleanedCPF.compactMap({ Int(String($0)) })
        
        // Primeiro dígito verificador
        let sum1 = calculateCPFCheckSum(cpfBaseDigits: Array(digits.prefix(9)), weight: 10)
        let dv1 = (sum1 * 10) % 11
        let expectedDV1 = (dv1 == 10) ? 0 : dv1
        
        // Segundo dígito verificador
        let sum2 = calculateCPFCheckSum(cpfBaseDigits: Array(digits.prefix(10)), weight: 11)
        let dv2 = (sum2 * 10) % 11
        let expectedDV2 = (dv2 == 10) ? 0 : dv2
        
        if digits[9] == expectedDV1 && digits[10] == expectedDV2 {
            return .valid
        } else {
            return .invalid
        }
    }
    
    private func generate() -> String {
        var digits = (0..<9).map { _ in Int.random(in: 0...9) }
        
        let sum1 = calculateCPFCheckSum(cpfBaseDigits: digits, weight: 10)
        let dv1 = (sum1 * 10) % 11
        digits.append(dv1 == 10 ? 0 : dv1)
        
        let sum2 = calculateCPFCheckSum(cpfBaseDigits: digits, weight: 11)
        let dv2 = (sum2 * 10) % 11
        digits.append(dv2 == 10 ? 0 : dv2)
        
        let generatedFakeCPF = digits.map({ String($0) }).joined()
        return validate(cpf: generatedFakeCPF) == .valid ? generatedFakeCPF : generate()
    }
    
    /// Generates a random valid CPF and returns it already formatted with the mask (XXX.XXX.XXX-XX).
    ///
    /// - Returns: The generated CPF formatted with the mask.
    ///
    /// - Warning: The CPF generated by this method is **valid** (based on CPF validation rules), but **it is not a real CPF**.
    ///   It does not correspond to a real person and should **not be used for any fraudulent, illegal, or deceptive purposes**.
    ///   This method is intended solely for **testing or simulation purposes** in development and software testing environments.
    ///
    /// **Example:**
    /// ```swift
    /// let cpfManager = CPFManager()
    /// let formattedCpf = cpfManager.generateMasked()
    /// print(formattedCpf)  // Example output: "111.444.777-35"
    /// ```
    public func generateMasked() -> String? {
        return format(generate())
    }
    
    private func format(_ cpf: String) -> String? {
        guard cpf.count == 11 else { return nil }
        return "\(cpf.prefix(3)).\(cpf.dropFirst(3).prefix(3)).\(cpf.dropFirst(6).prefix(3))-\(cpf.suffix(2))"
    }
    
    private func calculateCPFCheckSum(cpfBaseDigits: [Int], weight: Int) -> Int {
        var currentWeight = weight
        var checkSum = 0
        for digit in cpfBaseDigits {
            checkSum += digit * currentWeight
            currentWeight -= 1
        }
        return checkSum
    }
    
    /// Masks a given CPF by adding typical separators `XXX.XXX.XXX-XX`.
    ///
    /// - Parameter cpf: The CPF to be masked. It may contain non-numeric characters.
    /// - Returns: The CPF masked in the format `XXX.XXX.XXX-XX`.
    public func mask(cpf: String) -> String {
        var originalText = cpf.replacingOccurrences(of: "[^0-9]", with: "", options: .regularExpression)
        if originalText.count > 11 { originalText = String(originalText.prefix(11)) }
        var maskedText = ""
        for (index, char) in originalText.enumerated() {
            if index == 3 || index == 6 { maskedText.append(".") }
            else if index == 9 { maskedText.append("-") }
            maskedText.append(char)
        }
        return maskedText
    }
}
